name: momentum24_app
description: Momentum Conference App build with Flutter
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=3.2.5 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    flutter_web_plugins:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    get_it: ^8.0.3
    http: ^1.3.0
    shared_preferences: ^2.5.2
    flutter_markdown: ^0.7.6
    intl: ^0.19.0 # Version required by flutter_localizations
    timeline_tile: ^2.0.0
    flutter_map: ^8.1.0
    latlong2: ^0.9.1
    url_launcher: ^6.3.1
    flutter_sanity_client:
        git:
            url: https://github.com/bkazula/flutter-sanity-client.git
            ref: main
    cached_network_image: ^3.4.1 # TODO: remove this dependency if it still does not work
    fast_cached_network_image: ^1.3.3+5
    sentry_flutter: ^8.13.2
    string_unescape: ^2.0.0
    package_info_plus: ^8.3.0
    persistent_bottom_nav_bar_v2: ^5.3.1
    cupertino_icons: ^1.0.8
    web: ^1.1.1
    flutter_svg: ^2.0.17
    google_fonts: ^6.2.1
    async: ^2.12.0 # Version required by flutter
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    mockito: ^5.4.5
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/images/
        - google_fonts/
