name: momentum24_app
description: Momentum Conference App build with Flutter
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18+3
  intl: ^0.18.1
  avatar_stack: ^1.2.0
  timeline_tile: ^2.0.0
  timeago: ^3.6.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  url_launcher: ^6.2.4
  flutter_sanity_client:
    git:
      url: https://github.com/bkazula/flutter-sanity-client.git
      ref: main
  cached_network_image: ^3.3.1
  sentry_flutter: ^7.16.0
  string_unescape: ^2.0.0
  package_info_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
