name: momentum24_app
description: Momentum Conference App build with Flutter
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=3.2.5 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    flutter_web_plugins:
        sdk: flutter
    get_it: ^7.6.8
    http: ^1.2.0
    shared_preferences: ^2.2.2
    flutter_markdown: ^0.6.22
    intl: ^0.19.0
    timeline_tile: ^2.0.0
    flutter_map: ^6.1.0
    latlong2: ^0.9.0
    flutter_map_cancellable_tile_provider: ^2.0.0
    url_launcher: ^6.2.4
    flutter_sanity_client:
        git:
            url: https://github.com/bkazula/flutter-sanity-client.git
            ref: main
    cached_network_image: ^3.3.1
    sentry_flutter: ^7.18.0
    string_unescape: ^2.0.0
    package_info_plus: ^5.0.1
    persistent_bottom_nav_bar_v2: ^5.2.3
    cupertino_icons: ^1.0.6
    web: ^0.4.2
    flutter_localizations:
        sdk: flutter
    flutter_svg: ^2.0.10+1
    google_fonts: ^6.2.1
    async: ^2.11.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.2
    mockito: ^5.4.4
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/images/
        - google_fonts/
