name: Momentum Build

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - master
    workflow_dispatch:
    repository_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        permissions:
            contents: write
            actions: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'refs/heads/master' }}

            - name: Determine version
              id: determine_version
              uses: ./.github/actions/version-bump
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Deploy
              uses: ./.github/actions/build-deploy
              with:
                sanity_project_id: ${{ secrets.SANITY_PROJECT_ID_MOMENTUM }}
                onesignal_appid: ${{ secrets.ONESIGNAL_APPID_MOMENTUM }}
                vercel_token: ${{ secrets.VERCEL_TOKEN }}
                vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
                vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_MOMENTUM }}
                sentry_dsn: ${{ secrets.SENTRY_DSN_MOMENTUM }}
                version: ${{ steps.determine_version.outputs.new_version }}
                analytics_id: 1
