name: Flutter Web CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'refs/heads/master' }}

    - name: Set up Flutter actions
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19'
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    # Build and deploy with vercel
    - name: Prepare yarn v2
      run: |
        corepack enable
        yarn set version stable

    - name: Build with Vercel using NPX
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }} && npx vercel build ${{ github.event_name == 'pull_request' && '' || '--prod'}} --token ${{ secrets.VERCEL_TOKEN }}


    - name: Deploy prebuilt with Vercel
      id: deploy
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        npx vercel deploy ${{ github.event_name == 'pull_request' && '' || '--prod'}} --prebuilt --token ${{ secrets.VERCEL_TOKEN }} &> deploy.log
        cat deploy.log
        echo "url=$(grep -m1 -o 'https://[a-zA-Z0-9-]*.vercel.app' deploy.log)" >> "$GITHUB_OUTPUT"

    - name: Comment Pull Request with URL
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          :rocket: Deployed to Vercel Preview URL: ${{ steps.deploy.outputs.url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.pull_request.number }}
